# Input/Output paths
reads_dir: "/user/brussel/109/vsc10945/home/scratch/winpcapoolseq/variantcalling/reads"
results_dir: "/user/brussel/109/vsc10945/home/scratch/winpcapoolseq/variantcalling/results"
reference: "/user/brussel/109/vsc10945/home/scratch/data/reference/RT/RT_genome.fna"

# Trimmomatic parameters
trimmomatic:
  leading: 3
  trailing: 3
  slidingwindow: "4:20"
  minlen: 36

