# Input/Output paths
reads_dir: "/user/brussel/109/vsc10945/home/scratch/data/reads/DNA/RL"
results_dir: "/user/brussel/109/vsc10945/home/scratch/SexDetect/results/RL"
reference: "/user/brussel/109/vsc10945/home/scratch/data/reference/RT/RT_genome.fna"

# Intervals for parallelization
chromosome_prefix: "NC"
contig_prefix: "NW"

