# Input/Output paths
reads_dir: "[Input Read Directory]"
results_dir: "[Output Directory]"
reference: "[Genome file path]"

# Intervals for parallelization
chromosome_prefix: "[Chromosome start pattern]"
contig_prefix: "[Contig start pattern]"

# Sex identification patterns 
male_pattern: "[pattern]"
female_pattern: "[pattern]"
